# Generated by Django 6.0.3 on 2026-05-25 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionExternalMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappers', to='football.competition')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.externalsource')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_competition_external_mapping_source_external_id')],
            },
        ),
        migrations.CreateModel(
            name='HeadCoachExternalMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100)),
                ('head_coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappers', to='football.headcoach')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.externalsource')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_head_coach_external_mapping_source_external_id')],
            },
        ),
        migrations.CreateModel(
            name='MatchExternalMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappers', to='football.match')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.externalsource')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_match_external_mapping_source_external_id')],
            },
        ),
        migrations.CreateModel(
            name='PlayerExternalMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappers', to='football.player')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.externalsource')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_player_external_mapping_source_external_id')],
            },
        ),
        migrations.CreateModel(
            name='TeamExternalMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.externalsource')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappers', to='football.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_team_external_mapping_source_external_id')],
            },
        ),
    ]
